const USER_ROLES = Object.freeze({
  SUPER_OWNER: "SUPER_OWNER",
  BRANCH_OWNER: "BRANCH_OWNER",
  ADMIN: "ADMIN",
  CASHIER: "CASHIER",
  TECHNICIAN: "TECHNICIAN",
  CASH_CUSTODIAN: "CASH_CUSTODIAN",
});

const OWNER_ADMIN_ROLES = Object.freeze([
  USER_ROLES.SUPER_OWNER,
  USER_ROLES.BRANCH_OWNER,
  USER_ROLES.ADMIN,
]);

const STAFF_ROLES = Object.freeze([
  USER_ROLES.CASHIER,
  USER_ROLES.TECHNICIAN,
  USER_ROLES.CASH_CUSTODIAN,
]);

const BRANCH_SCOPED_ROLES = Object.freeze([
  USER_ROLES.BRANCH_OWNER,
  USER_ROLES.ADMIN,
  USER_ROLES.CASHIER,
  USER_ROLES.TECHNICIAN,
  USER_ROLES.CASH_CUSTODIAN,
]);

module.exports = {
  USER_ROLES,
  OWNER_ADMIN_ROLES,
  STAFF_ROLES,
  BRANCH_SCOPED_ROLES,
};
